use_frameworks!

platform :ios, '9.0'

target 'DRPickerViews_Example' do
  pod 'DRPickerViews', :path => '../'
  pod 'YYModel'
  pod 'BlocksKit'
  pod 'AFNetworking'

  target 'DRPickerViews_Tests' do
    inherit! :search_paths

    
  end
end
